#!/usr/bin/env python3
"""Quality filtering + exact and MinHash near-dedup over the harvest manifest.

Reads  data/work/harvest_manifest.jsonl  (from github_harvest.py)
Writes data/work/filtered_manifest.jsonl (surviving files, license carried)
       data/work/filter_stats.json       (funnel counters for stats.py)

Filter order (cheapest first, every rejection counted):
  1. size bounds            — tiny stubs / vendored blobs
  2. line-shape bounds      — minified or machine-formatted code
  3. alphanumeric fraction  — binary-ish / table-like files
  4. generated-code markers — bindgen/protobuf/"DO NOT EDIT" output
  5. exact dedup            — sha256 of whitespace-normalized text
  6. MinHash near-dedup     — datasketch LSH on 7-token shingles, Jaccard ~0.85
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from datasketch import MinHash, MinHashLSH

MIN_BYTES, MAX_BYTES = 256, 65536
MAX_AVG_LINE, MAX_LINE = 120, 1000
MIN_ALNUM_FRAC = 0.25
NUM_PERM = 128
JACCARD_THRESHOLD = 0.85
SHINGLE = 7

GENERATED_MARKERS = (
    "@generated", "do not edit", "automatically generated",
    "autogenerated", "auto-generated", "generated by rust-bindgen",
    "generated by prost", "this file is generated",
)

_token_re = re.compile(r"\w+")


def quality_reject_reason(text: str) -> str | None:
    n = len(text.encode("utf-8", errors="ignore"))
    if n < MIN_BYTES:
        return "too_small"
    if n > MAX_BYTES:
        return "too_large"
    lines = text.splitlines()
    if not lines:
        return "too_small"
    if max(len(l) for l in lines) > MAX_LINE:
        return "long_line"
    if sum(len(l) for l in lines) / len(lines) > MAX_AVG_LINE:
        return "long_avg_line"
    alnum = sum(c.isalnum() for c in text)
    if alnum / max(len(text), 1) < MIN_ALNUM_FRAC:
        return "low_alnum"
    head = text[:4096].lower()
    if any(m in head for m in GENERATED_MARKERS):
        return "generated"
    return None


def normalized_sha(text: str) -> str:
    return hashlib.sha256(" ".join(text.split()).encode()).hexdigest()


def minhash_of(text: str) -> MinHash:
    toks = _token_re.findall(text)
    mh = MinHash(num_perm=NUM_PERM)
    for i in range(max(len(toks) - SHINGLE + 1, 1)):
        mh.update(" ".join(toks[i:i + SHINGLE]).encode())
    return mh


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workdir", type=Path, default=Path("data/work"))
    args = ap.parse_args()

    records = [json.loads(l) for l in
               (args.workdir / "harvest_manifest.jsonl").open()]
    funnel = {"input": len(records)}
    rejects: dict[str, int] = {}

    # 1-4: per-file quality
    survivors = []
    for rec in records:
        text = Path(rec["path"]).read_text(encoding="utf-8")
        reason = quality_reject_reason(text)
        if reason:
            rejects[reason] = rejects.get(reason, 0) + 1
            continue
        rec["_text"] = text
        survivors.append(rec)
    funnel["after_quality"] = len(survivors)

    # 5: exact dedup (first occurrence wins; manifest order is sources.yaml
    # order, so curated-priority crates win ties)
    seen: set[str] = set()
    uniq = []
    for rec in survivors:
        h = normalized_sha(rec["_text"])
        if h in seen:
            rejects["exact_dup"] = rejects.get("exact_dup", 0) + 1
            continue
        seen.add(h)
        rec["sha_norm"] = h
        uniq.append(rec)
    funnel["after_exact_dedup"] = len(uniq)

    # 6: MinHash near-dedup
    lsh = MinHashLSH(threshold=JACCARD_THRESHOLD, num_perm=NUM_PERM)
    kept = []
    for i, rec in enumerate(uniq):
        mh = minhash_of(rec["_text"])
        if lsh.query(mh):
            rejects["near_dup"] = rejects.get("near_dup", 0) + 1
            continue
        lsh.insert(str(i), mh)
        kept.append(rec)
    funnel["after_near_dedup"] = len(kept)

    with open(args.workdir / "filtered_manifest.jsonl", "w") as out:
        for rec in kept:
            rec.pop("_text")
            out.write(json.dumps(rec) + "\n")
    stats = {"funnel": funnel, "rejects": rejects}
    (args.workdir / "filter_stats.json").write_text(json.dumps(stats, indent=2))
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
